name: Clang-tidy

on:
  push:
    branches: [ master, feature/14-add-cuda-to-the-project ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-tidy
      uses: HorstBaerbel/action-clang-tidy@1.2
      with:
        scandir: '.'
        excludedirs: ''
        extensions: 'c,h,cpp,hpp,cu,cuh'
        cmakeoptions: ''