# Compile project on Ubuntu
name: Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            cuda: "12.4"
            gcc: 12
    env:
      algorithms_to_test: quasi-mcp-cpu mcp-cpu
      build_dir: ./build/release

    steps:
    - uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl build-essential sudo \
          autoconf automake \
          zlib1g-dev libbz2-dev liblzma-dev \
          libcurl4-gnutls-dev libssl-dev cmake
      shell: bash

    - name: Install CUDA
      env:
        cuda: ${{ matrix.cuda }}
      run: ./scripts/install_cuda_ubuntu.sh
      shell: bash

    - name: Install dependencies
      run: ./scripts/install_libs.sh install
      shell: bash

    # Specify the correct host compilers
    - name: Install/Select gcc and g++
      run: |
        sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}
        echo "CC=/usr/bin/gcc-${{ matrix.gcc }}" >> "$GITHUB_ENV"
        echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> "$GITHUB_ENV"
        echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> "$GITHUB_ENV"

    - name: Configure cmake
      id: configure
      run: cmake --preset ci-gcc-x64-release

    - name: Configure Error Processing
      if: ${{ failure() && steps.configure.outcome == 'failure' }}
      run: |
          if [[ -d "${{ env.build_dir }}" ]]; then
            pushd "${{ env.build_dir }}"
            if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
              echo "---- CMakeFiles/CMakeOutput.log"
              cat CMakeFiles/CMakeOutput.log
              echo "----"
            fi
            if [[ -f "CMakeFiles/CMakeError.log" ]]; then
              echo "---- CMakeFiles/CMakeError.log"
              cat CMakeFiles/CMakeError.log
              echo "----"
            fi
          fi

    - name: Build
      run: cmake --build --preset ci-gcc-x64-release --verbose -j $(nproc)

    - name: Clang-tidy check
      run: ./scripts/run-clang-tidy.sh

    - name: Run tests
      working-directory: ${{ env.build_dir }}
      run: ./src/genome-downsampler test -a ${{ env.algorithms_to_test }}

